import React from 'react'


const App = () => {
    return (
        <div style={{
            paddingInline: "5rem",
            paddingTop: "2rem",
            paddingBottom: "2rem",
            fontFamily: "sans-serif"
        }}>
            <h1 style={{margin:"1rem 0 1rem 0"}}>Privacy Policy for MyHandydash</h1>
            <p>Last updated: September 24, 2025</p>
            <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

            <h2>1. Interpretation and Definitions</h2>
            <h3>Interpretation</h3>
            <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

            <h3>Definitions</h3>
            <ul>
                <li><strong>Account</strong> means a unique account created for You to access Our Service.</li>
                <li><strong>Application</strong> refers to MyHandydash, the software program provided by the Company.</li>
                <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our") refers to Handysolver, C 705, Pioneer Urban Square Golf Course Extension Road, Sector 62, Gurugram, Haryana, India - 122101.</li>
                <li><strong>Device</strong> means any device that can access the Service, such as a cellphone or a digital tablet.</li>
                <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                <li><strong>Service</strong> refers to the Application.</li>
                <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, or to assist the Company in analyzing how the Service is used.</li>
                <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service.</li>
            </ul>

            <h2>2. Collecting and Using Your Personal Data</h2>
            <h3>Types of Data Collected</h3>
            <h4>Personal Data</h4>
            <p>While using Our Service, We may collect the following Personal Data, with Your prior permission:</p>
            <ul>
                <li><strong>Name and Phone Number:</strong> Used for creating and managing Your account and for secure login.</li>
                <li><strong>Location Information:</strong> The Application collects Your precise location in the background to enable geo-fencing functionality. This is a core feature that allows You to "Mark In" or "Mark Out" only when You are within a pre-defined work location. Your location is collected only when you are "Marked In" to provide accurate attendance and tracking for your organization.</li>
                <li><strong>Facial Data:</strong> We use your device's camera to capture a facial image for the purpose of identity verification when you mark attendance. The captured image is immediately sent to a third-party Service Provider, Face++, to perform face detection and recognition. Face++ provides us with a unique Facial Token which is then stored in our database.

When you "Mark IN" or "Mark OUT" with facial verification enabled, we send a newly captured image to Face++ to generate another Facial Token. We then use Face++'s face comparison service to compare this new token with the stored token. Based on a similarity score, we verify your identity and allow the attendance to be marked.

The facial images themselves are not stored on our servers. However, the facial tokens are stored to facilitate future comparisons. This data is used solely for attendance verification and is not used for any other purpose. For more information, please review the Face++ Privacy Policy at <a href="https://www.faceplusplus.com/privacy-policy/" target="_blank">https://www.faceplusplus.com/privacy-policy/</a>.</li>
                <li><strong>Usage Data:</strong> Information such as Your Device's IP address, device type, mobile operating system, and unique device identifiers are collected to monitor and analyze the use of the Service.</li>
            </ul>

            <h3>Use of Your Personal Data</h3>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul>
                <li><strong>To provide and maintain the Service:</strong> To enable the core functions of the application, including attendance tracking, location-based services, and team chat.</li>
                <li><strong>To manage Your Account:</strong> To manage Your registration as a user and to provide You with access to the Service's functionalities.</li>
                <li><strong>For Your Organization:</strong> Your data is shared with Your organization's administrator to provide them with attendance records, location information, and other data for employee management purposes.</li>
                <li><strong>To contact You:</strong> To provide essential updates, security alerts, and information related to the Service.</li>
                <li><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, acquisition, or sale of our assets.</li>
                <li><strong>For other purposes:</strong> We may use Your information for data analysis, identifying usage trends, and to evaluate and improve our Service.</li>
            </ul>

            <h2>3. Your Data Deletion Rights</h2>
            <p>You have the right to request the deletion of Your Personal Data. As an employee attendance application, your data is primarily managed by your organization's administrator.</p>
            <p>To request data deletion, you must submit a request through our dedicated form. We will forward your request to your administrator for review and processing in accordance with our terms.</p>
            <ul>
                <li><strong>Data Deletion Request Form:</strong> <a href="https://handysolver.myhandydash.com/backend/web/web-page-builder/website/T7P5PmgXyxTWlobQuJMM" target="_blank">https://handysolver.myhandydash.com/backend/web/web-page-builder/website/T7P5PmgXyxTWlobQuJMM</a></li>
            </ul>

            <h2>4. Security of Your Personal Data</h2>
            <p>The security of Your Personal Data is important to Us. While We use commercially acceptable means to protect Your data, no method of transmission over the Internet or electronic storage is 100% secure. We cannot guarantee its absolute security.</p>

            <h2>5. Children's Privacy</h2>
            <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that we have collected Personal Data from a child under 13 without verification of parental consent, we will take steps to remove that information from Our servers.</p>

            <h2>6. Links to Other Websites</h2>
            <p>Our Service may contain links to other websites that are not operated by Us. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services. We strongly advise You to review the Privacy Policy of every site You visit.</p>

            <h2>7. Changes to this Privacy Policy</h2>
            <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date at the top. You are advised to review this Privacy Policy periodically for any changes. Changes are effective when they are posted on this page.</p>

            <h2>8. Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, You can contact us:</p>
            <ul>
                <li><strong>By email:</strong> connect@handysolver.com</li>
            </ul>
        </div>
    )
}

export default App;